### ISSUE TITLE
throwing errors when using Server Side Rendering (angular 6 universal)

### ISSUE THREAD

**Issue by cs-eddy** [andreasonny83/angular2-cookie-law#29]
ERROR ReferenceError: document is not defined
    at Angular2CookieLawService.seen (/Users/Desktop/stack-website/development/src/frontend/node_modules/angular2-cookie-law/bundles/angular2-cookie-law.umd.js:26:48)
    at CookieLawContainerComponent.ngOnInit (/Users/Desktop/stack-website/development/src/frontend/node_modules/angular2-cookie-law/bundles/angular2-cookie-law.umd.js:284:51)
....

**Comment by exequiel09** [comment]
I'll take a look on this and see what i can do :)

**Comment by Bidthedog** [comment]
Getting the same issue - could do with the PR being merged!
